ZSH=$HOME/.oh-my-zsh
# ZSH_CUSTOM=$HOME/lib/oh-my-zsh_custom
ZSH_THEME="t1"
CASE_SENSITIVE="true"
DISABLE_CORRECTION="true"
HIST_STAMPS="yyyy-mm-dd"
plugins=(bundler colored-man common-aliases debian gem git rails screen)
source $ZSH/oh-my-zsh.sh

PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init - zsh)"

[ -d "$HOME/bin" ] && export PATH="$HOME/bin:$PATH"
